version: '3.8'
services:
  service1:
    image: neinomas/prize-gen-service1
    build: ./service-1-frontend
    ports:
    - "5000:5000"
  services2 :
    image: neinomas/prize-gen-services2
    build: ./service-2-char-gen
  services3 :
    image: neinomas/prize-gen-service3
    build: ./service-3-num-gen
  services4 :
    image: neinomas/prize-gen-service4
    build: ./service-4-prize-gen
  nginx:
    image: nginx:latest
    ports:
    - target: 80
      published: 80
      protocol: tcp
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf