version: '3.8'
services:
  service1:
    image: neinomas/prize-gen-service1
    build: ./service-1-frontend
    ports:
    - target: 5000
    environment:
      - DATABASE_URI=mysql+pymysql://root:${rootpass}@db/db
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - db
  service2:
    image: neinomas/prize-gen-services2
    build: ./service-2-char-gen
  service3:
    image: neinomas/prize-gen-service3
    build: ./service-3-num-gen
  service4:
    image: neinomas/prize-gen-service4
    build: ./service-4-prize-gen
  nginx:
    image: nginx:latest
    ports:
    - target: 80
      published: 80
      protocol: tcp
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
  db:
    image: neinomas/db
    build: ./db
    ports:
      - target: 3306
    environment:
      - MYSQL_ROOT_PASSWORD=${rootpass}
    volumes: 
      - my-datavolume:/var/lib/mysql
volumes: 
  my-datavolume: