version: '3.8'
services:
  service1:
    image: neinomas/prize-gen-service1:${app_version}
    build: ./service-1-frontend
    deploy:
      replicas: 2
    ports:
    - target: 5000
    environment:
      - DATABASE_URI=mysql+pymysql://root:${rootpass}@db/db
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - db
  service2:
    image: neinomas/prize-gen-service2:${app_version}
    build: ./service-2-char-gen
    deploy:
      replicas: 2
  service3:
    image: neinomas/prize-gen-service3:${app_version}
    build: ./service-3-num-gen
    deploy:
      replicas: 2
  service4:
    image: neinomas/prize-gen-service4:${app_version}
    build: ./service-4-prize-gen
    deploy:
      replicas: 2
  nginx:
    image: nginx:latest
    ports:
    - target: 80
      published: 80
      protocol: tcp
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
  db:
    image: neinomas/db
    build: ./db
    ports:
      - target: 3306
    environment:
      - MYSQL_ROOT_PASSWORD=${rootpass}
    volumes: 
      - my-datavolume:/var/lib/mysql
volumes: 
  my-datavolume: