---
# tasks file for swarm-join
- name: Add Workers to the Swarm
  docker_swarm:
    state: join
    advertise_addr: worker
    join_token: "{{ hostvars['10.132.0.9']['swarm_info']['swarm_facts']['JoinTokens']['Worker'] }}"
    remote_addrs: [ 'swarm-manager:2377' ] 
