all:
  children:
    swarm-manager:
      hosts:
        10.132.0.9:
    swarm-worker:
      hosts:
        10.132.0.10:
  vars:
    ansible_user: wistyhodgson
    ansible_ssh_private_key_file: "/home/wistyhodgson/id_rsa"
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
    ansible_python_interpreter: "/usr/bin/python3"
